import Navbar from "./Navbar"
import '../styles/globals.css'

import App from "next/app"
import NavBar from "./Navbar"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@100;200;300;400;700&family=Bellefair&display=swap" rel="stylesheet"/>
      </head>
      <body>
      <NavBar/>
        {children}
        </body>
    </html>
  )
}
